In [1]:
import numpy as np

arr = np.array([5,15,10,25])
print(arr.shape)
print(arr.dtype)





(4,)
int64


In [13]:
arr1=np.zeros((3,3))
print(arr1)

arr2=np.ones((2,4))
print(arr2)

arr3= np.arange(1,11)
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[ 1  2  3  4  5  6  7  8  9 10]


In [14]:
print(np.identity(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
ar=np.arange(1,13)
print(ar)
print(ar.reshape(3,4))
print(ar.reshape(4,3))
print(ar.reshape(2,6))


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [ ]:
ab=np.arange(1,9)
print(ab)
print(ab.reshape(-1,1))
print(ab.reshape(2,4))
print(ab.reshape(1,-1))

[1 2 3 4 5 6 7 8]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4 5 6 7 8]]


In [3]:
bc=np.random.randint(10,100, size=10)
print(bc)
#print(bc.reshape(3,4))

[68 35 91 87 22 17 17 44 30 27]


In [8]:
matrix=np.array([ [[10, 20, 30],
 [40, 50, 60],
 [70, 80, 90]]
])
print(matrix)
print()
print(matrix[:,1,:])
print()
print(matrix[:,:,2].reshape(-1,1))
print()
print(matrix[0,1,1])
print()
matrix[0,2,2,]=100
print(matrix)

[[[10 20 30]
  [40 50 60]
  [70 80 90]]]

[[40 50 60]]

[[30]
 [60]
 [90]]

50

[[[ 10  20  30]
  [ 40  50  60]
  [ 70  80 100]]]


In [10]:
mat=np.random.randint(1,10,size=(3,2))
print(mat)
print(mat.transpose())

[[3 6]
 [4 8]
 [9 3]]
[[3 4 9]
 [6 8 3]]


In [12]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
res = a.flatten()
print(res)

[1 2 3 4 5 6]


In [14]:
arr=np.array([12,15,20,22,18,25,30])
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))

20.285714285714285
20.0
5.624291338579865


In [17]:
matrix=np.random.randint(1,10,size=(3,3))
print(matrix)
row_means=np.mean(matrix, axis=1)
print(row_means)
col_means=np.mean(matrix, axis=0)
print(col_means)


[[1 2 3]
 [7 2 9]
 [4 7 3]]
[2.         6.         4.66666667]
[4.         3.66666667 5.        ]
